version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: ca-api-mysql
    ports:
      - 4306:3306
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ca-api-phpmyadmin
    ports:
      - 4000:80
    platform: linux/x86_64
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: "password"
    links:
      - mysql

volumes:
  db-data:
    driver: local
